### ISSUE TITLE
Prototype "motherboards" has been made for ESP32, STM32F103 (Bluepill) and SAMD21 (MKRZERO)

### ISSUE THREAD

**Issue by psyhlo** [terjeio/CNC_Boosterpack#2]
As it is written in README
would you share the rest? I would like to use ESP32 or Bluepill

**Comment by terjeio** [comment]
I have done a bit of touch-up on the prototypes, these are two layer boards - orginials were one layer with bodge wires.
Note that they are untested and may not work correctly...
The ESP32 and STM103 boards has an option for a SD card socket - I believe I bought them from Farnell. I can try to find the part number if of interest, or perhaps better swap the footprint to whatever you fancy.

Files are in Kicad 5 format:

[ESP32 CNC Mobo.zip](https://github.com/terjeio/CNC_Boosterpack/files/11967001/ESP32.CNC.Mobo.zip)

[MKRZERO CNC Mobo.zip](https://github.com/terjeio/CNC_Boosterpack/files/11967004/MKRZERO.CNC.Mobo.zip)

[STM103F1xx CNC Mobo.zip](https://github.com/terjeio/CNC_Boosterpack/files/11967007/STM103F1xx.CNC.Mobo.zip)

**Comment by psyhlo** [comment]
thanks 
i'll have a try with them
